[options]
admin_passwd = $pbkdf2-sha512$600000$TokRovSeEwKA0BrDGGMshQ$KX3jVMl1ZNWk..mriJIaklqHhH//nsu/BrrDzfE.yUSnyCknCGf0gYMXAAh1JYW8nhLSyoyq6C4YuuHk2y2AoQ
db_user = odoo
db_password = admin
addons_path = C:\Users\baluc\Documents\projects\odoo\odoo\addons,C:\Users\baluc\Documents\projects\odoo\Final\dubai-tourism-erp
default_productivity_apps = True

